package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Promote30_Snapshot'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Promote30_Snapshot")) {
    requirements {
        add {
            contains("teamcity.agent.name", "dev", "RQ_4")
        }
    }
}
